# Generated by Django 4.2.4 on 2023-08-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completion_date", models.DateField(null=True)),
                ("street_address", models.CharField(max_length=200)),
                ("stair", models.CharField(max_length=16)),
                ("floor", models.IntegerField(null=True)),
                ("apartment_number", models.PositiveIntegerField()),
                ("shares_start", models.PositiveIntegerField(null=True)),
                ("shares_end", models.PositiveIntegerField(null=True)),
                ("surface_area", models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ("rooms", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
                "ordering": ["street_address", "stair", "-apartment_number"],
            },
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Developer",
                "verbose_name_plural": "Developers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HousingCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="housing_companies",
                        to="example.developer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Housing company",
                "verbose_name_plural": "Housing companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("identifier", models.CharField(blank=True, max_length=11, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name": "Postal code",
                "verbose_name_plural": "Postal codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PropertyManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Property manager",
                "verbose_name_plural": "Property managers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purchase_date", models.DateField(editable=False)),
                ("purchase_price", models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                (
                    "apartment",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="example.apartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("surface_area", models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                (
                    "housing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="real_estates",
                        to="example.housingcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Real estate",
                "verbose_name_plural": "Real estates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("percentage", models.DecimalField(decimal_places=0, editable=False, max_digits=3)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownerships",
                        to="example.owner",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="example.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ownership",
                "verbose_name_plural": "Ownership",
            },
        ),
        migrations.AddField(
            model_name="housingcompany",
            name="postal_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="housing_companies", to="example.postalcode"
            ),
        ),
        migrations.AddField(
            model_name="housingcompany",
            name="property_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="housing_companies",
                to="example.propertymanager",
            ),
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("street_address", models.CharField(max_length=200)),
                (
                    "real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="buildings", to="example.realestate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="apartment",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="apartments", to="example.building"
            ),
        ),
    ]
