# Generated by Django 4.2.10 on 2024-02-28 17:58

from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType
from ..models import HousingCompany, PropertyManager, TaggedItem

import random
import django.db.models.deletion


def make_data(apps, schema_editor):

    tags = []

    architecture_types = ["modern", "gothic", "classic", "neoclassical", "islamic"]
    for hc in HousingCompany.objects.all():
        tag = TaggedItem(
            object_id=hc.id,
            content_type=ContentType.objects.get_for_model(HousingCompany),
            tag=random.choice(architecture_types),
            confidence=random.random() * 100
        )
        tags.append(tag)

    property_manager_types = ["hard-hitting", "noob", "amateur", "pro", "high-potential"]
    for pm in PropertyManager.objects.all():
        tag = TaggedItem(
            object_id=pm.id,
            content_type=ContentType.objects.get_for_model(PropertyManager),
            tag=random.choice(property_manager_types),
            confidence=random.random() * 100
        )
        tags.append(tag)

    TaggedItem.objects.bulk_create(tags)


def delete_data(apps, schema_editor):
    TaggedItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('confidence', models.FloatField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='example_tag_content_427210_idx')],
            },
        ),
        migrations.RunPython(make_data, delete_data)
    ]
