# Generated by Django 4.2.8 on 2023-12-29 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0002_apartmentproxy_housingcompanyproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("example.building",),
        ),
        migrations.CreateModel(
            name="RealEstateProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("example.realestate",),
        ),
    ]
