name: Bug Report
description: File a bug report.
labels:
  - bug
body:
  - type: markdown
    id: thank-you
    attributes:
      value: |
        Thank you for your interest in the library!
  - type: checkboxes
    id: docs-read
    attributes:
      label: I have read the docs thoroughly before making this bug report.
      description: >-
        Docs can be found [here](https://mrthearman.github.io/graphene-django-query-optimizer/).
      options:
        - label: "Yes"
          required: true
  - type: checkboxes
    id: other-issues
    attributes:
      label: I have read through other open issues, and my issue is not a duplicate.
      description: >-
        Open issues can be found [here](https://github.com/MrThearMan/graphene-django-query-optimizer/issues).
      options:
        - label: "Yes"
          required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of the library you are using?
      description: >-
        Please note that library versions not available below are not supported.
        If you are not using the latest version, please try to also reproduce the bug
        on the latest version before opening the issue.
      options:
        - "0.0.1"
    validations:
      required: true
  - type: dropdown
    id: python
    attributes:
      label: Which python version are you using?
      description: >-
        Please note that python versions not available below are not supported.
      options:
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you on?
      description: >-
        Please note operating systems not available below may not be supported.
        Only the latest versions of these operating systems are tested.
      options:
        - "Windows"
        - "Mac"
        - "Ubuntu"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: >-
        Give detailed steps on how to reproduce the bug from a new virtual environment.
        Error tracebacks are appreciated (unabridged when possible).
        Do not use pictures to include the error, add [code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) instead.
    validations:
      required: true
