name: Release

on:
  release:
    types:
      - released

jobs:
  release:
    uses: MrThearMan/CI/.github/workflows/release.yml@v0.4.13
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
    with:
      poetry-version: "2.0.0"
